PocSistemaAcademico-war/src/java/br/com/jsf/UsuarioPermissaoController.java
package br.com.jsf;

import br.com.jpa.entities.UsuarioPermissao;
import br.com.jsf.util.JsfUtil;
import br.com.jsf.util.PaginationHelper;
import br.com.jpa.session.UsuarioPermissaoFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("usuarioPermissaoController")
@SessionScoped
public class UsuarioPermissaoController implements Serializable {

    private UsuarioPermissao current;
    private DataModel items = null;
    @EJB
    private br.com.jpa.session.UsuarioPermissaoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public UsuarioPermissaoController() {
    }

    public UsuarioPermissao getSelected() {
        if (current == null) {
            current = new UsuarioPermissao();
            current.setUsuarioPermissaoPK(new br.com.jpa.entities.UsuarioPermissaoPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private UsuarioPermissaoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (UsuarioPermissao) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new UsuarioPermissao();
        current.setUsuarioPermissaoPK(new br.com.jpa.entities.UsuarioPermissaoPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getUsuarioPermissaoPK().setUsuarioId(current.getUsuario().getUsuarioId());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("UsuarioPermissaoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (UsuarioPermissao) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getUsuarioPermissaoPK().setUsuarioId(current.getUsuario().getUsuarioId());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("UsuarioPermissaoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (UsuarioPermissao) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("UsuarioPermissaoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public UsuarioPermissao getUsuarioPermissao(br.com.jpa.entities.UsuarioPermissaoPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = UsuarioPermissao.class)
    public static class UsuarioPermissaoControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            UsuarioPermissaoController controller = (UsuarioPermissaoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "usuarioPermissaoController");
            return controller.getUsuarioPermissao(getKey(value));
        }

        br.com.jpa.entities.UsuarioPermissaoPK getKey(String value) {
            br.com.jpa.entities.UsuarioPermissaoPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new br.com.jpa.entities.UsuarioPermissaoPK();
            key.setUsuarioId(Integer.parseInt(values[0]));
            key.setPermissao(values[1]);
            return key;
        }

        String getStringKey(br.com.jpa.entities.UsuarioPermissaoPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getUsuarioId());
            sb.append(SEPARATOR);
            sb.append(value.getPermissao());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof UsuarioPermissao) {
                UsuarioPermissao o = (UsuarioPermissao) object;
                return getStringKey(o.getUsuarioPermissaoPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + UsuarioPermissao.class.getName());
            }
        }

    }

}

PocSistemaAcademico-war/web/usuarioPermissao/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateUsuarioPermissaoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateUsuarioPermissaoLabel_usuarioPermissaoPK_permissao}" for="usuarioPermissaoPK_permissao" />
                    <h:inputText id="usuarioPermissaoPK_permissao" value="#{usuarioPermissaoController.selected.usuarioPermissaoPK.permissao}" title="#{bundle.CreateUsuarioPermissaoTitle_usuarioPermissaoPK_permissao}" required="true" requiredMessage="#{bundle.CreateUsuarioPermissaoRequiredMessage_usuarioPermissaoPK_permissao}"/>
                    <h:outputLabel value="#{bundle.CreateUsuarioPermissaoLabel_usuario}" for="usuario" />
                    <h:selectOneMenu id="usuario" value="#{usuarioPermissaoController.selected.usuario}" title="#{bundle.CreateUsuarioPermissaoTitle_usuario}" required="true" requiredMessage="#{bundle.CreateUsuarioPermissaoRequiredMessage_usuario}">
                        <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuarioPermissaoController.create}" value="#{bundle.CreateUsuarioPermissaoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{usuarioPermissaoController.prepareList}" value="#{bundle.CreateUsuarioPermissaoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateUsuarioPermissaoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

PocSistemaAcademico-war/web/usuarioPermissao/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditUsuarioPermissaoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditUsuarioPermissaoLabel_usuarioPermissaoPK_permissao}" for="usuarioPermissaoPK_permissao" />
                    <h:inputText id="usuarioPermissaoPK_permissao" value="#{usuarioPermissaoController.selected.usuarioPermissaoPK.permissao}" title="#{bundle.EditUsuarioPermissaoTitle_usuarioPermissaoPK_permissao}" required="true" requiredMessage="#{bundle.EditUsuarioPermissaoRequiredMessage_usuarioPermissaoPK_permissao}"/>
                    <h:outputLabel value="#{bundle.EditUsuarioPermissaoLabel_usuario}" for="usuario" />
                    <h:selectOneMenu id="usuario" value="#{usuarioPermissaoController.selected.usuario}" title="#{bundle.EditUsuarioPermissaoTitle_usuario}" required="true" requiredMessage="#{bundle.EditUsuarioPermissaoRequiredMessage_usuario}">
                        <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{usuarioPermissaoController.update}" value="#{bundle.EditUsuarioPermissaoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditUsuarioPermissaoViewLink}"/>
                <br />
                <h:commandLink action="#{usuarioPermissaoController.prepareList}" value="#{bundle.EditUsuarioPermissaoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditUsuarioPermissaoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

PocSistemaAcademico-war/web/usuarioPermissao/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListUsuarioPermissaoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListUsuarioPermissaoEmpty}" rendered="#{usuarioPermissaoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{usuarioPermissaoController.items.rowCount > 0}">
                    <h:outputText value="#{usuarioPermissaoController.pagination.pageFirstItem + 1}..#{usuarioPermissaoController.pagination.pageLastItem + 1}/#{usuarioPermissaoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{usuarioPermissaoController.previous}" value="#{bundle.Previous} #{usuarioPermissaoController.pagination.pageSize}" rendered="#{usuarioPermissaoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{usuarioPermissaoController.next}" value="#{bundle.Next} #{usuarioPermissaoController.pagination.pageSize}" rendered="#{usuarioPermissaoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{usuarioPermissaoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioPermissaoTitle_usuarioPermissaoPK_permissao}"/>
                            </f:facet>
                            <h:outputText value="#{item.usuarioPermissaoPK.permissao}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUsuarioPermissaoTitle_usuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.usuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{usuarioPermissaoController.prepareView}" value="#{bundle.ListUsuarioPermissaoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usuarioPermissaoController.prepareEdit}" value="#{bundle.ListUsuarioPermissaoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{usuarioPermissaoController.destroy}" value="#{bundle.ListUsuarioPermissaoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{usuarioPermissaoController.prepareCreate}" value="#{bundle.ListUsuarioPermissaoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListUsuarioPermissaoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

PocSistemaAcademico-war/web/usuarioPermissao/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewUsuarioPermissaoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewUsuarioPermissaoLabel_usuarioPermissaoPK_permissao}"/>
                    <h:outputText value="#{usuarioPermissaoController.selected.usuarioPermissaoPK.permissao}" title="#{bundle.ViewUsuarioPermissaoTitle_usuarioPermissaoPK_permissao}"/>
                    <h:outputText value="#{bundle.ViewUsuarioPermissaoLabel_usuario}"/>
                    <h:outputText value="#{usuarioPermissaoController.selected.usuario}" title="#{bundle.ViewUsuarioPermissaoTitle_usuario}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuarioPermissaoController.destroyAndView}" value="#{bundle.ViewUsuarioPermissaoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewUsuarioPermissaoEditLink}"/>
                <br />
                <h:commandLink action="#{usuarioPermissaoController.prepareCreate}" value="#{bundle.ViewUsuarioPermissaoCreateLink}" />
                <br />
                <h:commandLink action="#{usuarioPermissaoController.prepareList}" value="#{bundle.ViewUsuarioPermissaoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewUsuarioPermissaoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>